### ISSUE TITLE
0.0.9 install broken

### ISSUE THREAD

**Issue by hyperknot** [ITCase/sacrud_deform#14]
```
Collecting sacrud-deform>=0.0.8 (from pyramid-sacrud->-r requirements/base.txt (line 14))
  Downloading sacrud_deform-0.0.9.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/bq/31skcq4168v9zcyv364zqpp00000gn/T/pip-build-dIuQ2u/sacrud-deform/setup.py", line 27, in <module>
        tests_require=read('requirements.txt') + read('requirements-test.txt'),
      File "/private/var/folders/bq/31skcq4168v9zcyv364zqpp00000gn/T/pip-build-dIuQ2u/sacrud-deform/setup.py", line 8, in read
        with open(os.path.join(here, name)) as f:
    IOError: [Errno 2] No such file or directory: '/private/var/folders/bq/31skcq4168v9zcyv364zqpp00000gn/T/pip-build-dIuQ2u/sacrud-deform/requirements-test.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/bq/31skcq4168v9zcyv364zqpp00000gn/T/pip-build-dIuQ2u/sacrud-deform
```

**Comment by uralbash** [comment]
Thank you, I fixed it on PyPi.
